/* Auto-generated by fonts/gen_gbk_table.py. Do not edit. */
#pragma once

#include <stdint.h>

/* GBK(936) -> Unicode, linear index (hi-0x81)*190 + folded_lo. */
/* 23940 entries, undefined cells are 0. */
extern const uint16_t solar_os_gbk_to_unicode[23940];
