#pragma once

#include <stdint.h>

/*
 * SolarOS pinyin IME lookup service.
 *
 * Provides candidate lookups over the static tables generated by
 * fonts/gen_ime_table.py.  The engine is pure data access: it has no
 * UI and no input state; callers (shell line editor, on-screen vkb)
 * own the pinyin accumulation state.
 *
 * Candidates are UTF-8 byte spans pointing into the readonly candidate
 * blob.  They are NOT null-terminated; use the returned len.
 */

/* A single candidate word/char (UTF-8 bytes, not null-terminated). */
typedef struct {
    const uint8_t *data;
    uint8_t len;
} solar_os_ime_candidate_t;

#define SOLAR_OS_IME_MAX_CANDIDATES 24
#define SOLAR_OS_IME_PINYIN_MAX 7
#define SOLAR_OS_IME_PAGE_SIZE 8

/*
 * Look up candidates for a pinyin string.
 *
 * Exact syllable match is tried first (e.g. "zhong").  When no exact
 * syllable exists the query falls back to a prefix match over all
 * syllables (e.g. "zhon" matches "zhong", "zhongjian"...).  Results are
 * de-duplicated and written to out in table order; returns the number
 * of candidates (0 when nothing matches).
 */
int solar_os_ime_lookup(const char *pinyin,
                        solar_os_ime_candidate_t *out,
                        int max_out);

/* Number of candidates for an exact syllable (0 when unknown). */
int solar_os_ime_exact_count(const char *pinyin);