#pragma once

#include "solar_os_expansion.h"

extern const solar_os_expansion_driver_t solar_os_ili9341_expansion_driver;
extern const solar_os_expansion_driver_t solar_os_st7796_expansion_driver;
extern const solar_os_expansion_driver_t solar_os_st7789_expansion_driver;
