/* Auto-generated by fonts/gen_ime_table.py. Do not edit. */
#pragma once

#include <stdint.h>

typedef struct {
    char pinyin[8];
    uint16_t cand_off;
    uint16_t cand_count;
} solar_os_ime_syllable_t;

extern const solar_os_ime_syllable_t solar_os_ime_syllables[];
extern const uint32_t solar_os_ime_syllable_count;
extern const uint8_t solar_os_ime_candidates[];
extern const uint32_t solar_os_ime_candidate_size;
