#!/usr/bin/env python3
"""Generate the GBK -> Unicode lookup table used by solar_os_text_gbk.c.

Produces src/services/solar_os_gbk_table.h containing:
    extern const uint16_t solar_os_gbk_to_unicode[23940];

Index = (hi - 0x81) * 190 + folded_lo, where folded_lo counts
0x40..0x7E (63) then 0x80..0xFE (127), skipping the 0x7F hole.
Undefined GBK cells map to 0.
"""
from __future__ import annotations

from pathlib import Path

OUT_H = Path(__file__).resolve().parents[1] / "src" / "services" / "solar_os_gbk_table.h"
OUT_C = Path(__file__).resolve().parents[1] / "src" / "services" / "solar_os_gbk_table.c"
HI_MIN, HI_MAX = 0x81, 0xFE
COLS = 190  # 0x40..0x7E + 0x80..0xFE
TOTAL = (HI_MAX - HI_MIN + 1) * COLS


def gbk_decode(hi: int, lo: int) -> int:
    try:
        return ord(bytes([hi, lo]).decode("gbk"))
    except (UnicodeDecodeError, LookupError):
        return 0


def main() -> int:
    values: list[int] = []
    for hi in range(HI_MIN, HI_MAX + 1):
        for lo in list(range(0x40, 0x7F)) + list(range(0x80, 0xFF)):
            values.append(gbk_decode(hi, lo))

    assert len(values) == TOTAL, len(values)

    lines_h = [
        "/* Auto-generated by fonts/gen_gbk_table.py. Do not edit. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"/* GBK(936) -> Unicode, linear index (hi-0x81)*190 + folded_lo. */",
        f"/* {TOTAL} entries, undefined cells are 0. */",
        f"extern const uint16_t solar_os_gbk_to_unicode[{TOTAL}];",
        "",
    ]
    OUT_H.write_text("\n".join(lines_h), encoding="ascii")

    per_line = 10
    lines_c = [
        "/* Auto-generated by fonts/gen_gbk_table.py. Do not edit. */",
        "",
        '#include "solar_os_gbk_table.h"',
        "",
        f"const uint16_t solar_os_gbk_to_unicode[{TOTAL}] = {{",
    ]
    for i in range(0, TOTAL, per_line):
        chunk = values[i:i + per_line]
        lines_c.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines_c.append("};")
    lines_c.append("")
    OUT_C.write_text("\n".join(lines_c), encoding="ascii")

    defined = sum(1 for v in values if v != 0)
    print(f"wrote {OUT_H} + {OUT_C} ({TOTAL} entries, {defined} defined)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
